### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by uimaxbai** [GoneRogueProductions/dispatchx#21]

**Comment by uimaxbai** [comment]
@thisiscoding1234 

I’ll do default and default dark theme

Themes you can do:

- @werdl inspired theme (Coder)
- Few VSC inspired themes
- Thought-of themes
- High-contrast themes (2)

Any more can be made

All themes need a dark mode

**Comment by thisiscoding1234** [comment]
<img src="https://github.com/GoneRogueProductions/dispatchx/assets/106704354/ee03eb3b-ca5c-4739-8f98-5f6bb7c609b5" style="width:16%;height:16%;"/>
<img src="https://github.com/GoneRogueProductions/dispatchx/assets/106704354/6a60a56b-22ef-4cac-a81b-4789e7357071" style="width:16%;height:16%;"/>
<img src="https://github.com/GoneRogueProductions/dispatchx/assets/106704354/d0edf280-344a-40af-953a-716fbcf9f39b" style="width:16%;height:16%;"/>
<img src="https://github.com/GoneRogueProductions/dispatchx/assets/106704354/60883888-011f-4362-b560-c124bd83e268" style="width:16%;height:16%;"/>
<img src="https://github.com/GoneRogueProductions/dispatchx/assets/106704354/0ce1cd45-2f1e-434d-835e-5246527f622e" style="width:16%;height:16%;"/>
<img src=" https://github.com/GoneRogueProductions/dispatchx/assets/106704354/10da4cb6-9be5-450a-a6a4-c3407cb46940" style="width:16%;height:16%;"/>

current themes
