### ISSUE TITLE
Fix code scanning alert - Inclusion of functionality from an untrusted source

### ISSUE THREAD

**Issue by thisiscoding1234** [GoneRogueProductions/dispatchx#32]
Tracking issue for:
- [ ] https://github.com/GoneRogueProductions/dispatchx/security/code-scanning/4
- [ ] also see https://github.com/GoneRogueProductions/dispatchx/security/code-scanning/3

can you fix this?

**Comment by uimaxbai** [comment]
Fixed by adding integrity checks.
